In [118]:
import numpy as np

In [150]:
import numpy as np
a = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])




## Problem 1

##### Solve the matrix product of A and B by hand

To find the matrix product of A and B, the number of columns of A should be equal to the number of columns in B

In this case both A and B are 3 by 3  matrices
By multiplying each row in A by each column in B
#### A.B = {
    (-1*0) + (2*0) + (3*2)     (-1*2) + (2*2) + (3*9)    (-1*1) + (2*8) + (3*-1)
    (1*0) + (-5*0) + (6*2)     (4*2) + (-5*2) + (6*9)     (4*1) + (-5*-8) + (6*-1)
    (7*0) + (8*0) + (-9*2)      (7*2) + (8*2) + (-9*9)     (7*1) + (8*-8) + (-9*-1)
}

#### A.B = {
    0+0+6       -2+4+27     -1-16-3
    0+0+12       8-10+27     4+40-6
    0+0-18       14+16-81    7-64+9
}

#### A.B = {
    6   29  -20
    12  52   38
    -18 -51  48
}


### Problem 2

In [151]:
matmul = np.matmul(a, b)

dot_product = np.dot(a, b)

at = a @ b

print(f"Using np.matmul: \n {matmul}\n")

print(f"Using dot method: \n {dot_product}\n")

print(f"Using @:\n {at}")

Using np.matmul: 
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

Using dot method: 
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

Using @:
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


### problem 3

In [156]:
result = []
c = b.T #tranposing b to make selection of column values easy
outer = 0
columns = a.shape[0]

"""The while loop runs (row a * row b.T) times, which is same
as (row a * column b) times because each row of a multiplies each column of b"""
while outer < columns:
    inner = 0
    rows = c.shape[0] # number of columns in transposed b
    while inner < rows:
        result.append((a[outer] * c[inner]).sum())
        inner += 1
    outer += 1
# because I transposed b, the shape of the new array is (row a, row b) 
result = np.array(result).reshape((a.shape[0], c.shape[0])) 
print(result)

print(f"Verifying my solution by comparing output using numpy inbuilt function \n {result == a@b}")

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
Verifying my solution by comparing output using numpy inbuilt function 
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### Problem 4

In [157]:
def mat_multiply(a, b):
    """Performs a matrix multiplication between a and b"""
    result = []
    b = b.T #tranposing b to make selection of column values easy
    outer = 0
    columns = a.shape[0]
    """The while loop runs (row a * row b.T) times, which is same
    as (row a * column b) times because each row of a multiplies each column of b"""
    while outer < columns:
        inner = 0
        rows = b.shape[0] # number of columns in transposed b
        while inner < rows:
            result.append((a[outer] * b[inner]).sum())
            inner += 1
        outer += 1
    # because I transposed b, the shape of the new array is (row a, row b) 
    result = np.array(result).reshape((a.shape[0], b.shape[0])) 
    return result

   


In [158]:
print(mat_multiply(a, b))



[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


### Problem 5

In [160]:
def mat_multiply(a, b):
    """Performs a matrix multiplication between a and b"""
    result = []
    c = b.T #tranposing b to make selection of column values easy
    outer = 0
    columns = a.shape[0]
    """The while loop runs (row a * row b.T) times, which is same
    as (row a * column b) times because each row of a multiplies each column of b"""
    try:
        if a.shape[1] != b.shape[0]:
            raise ValueError
    except ValueError:
        
        print(f"Number of columns in A: {a.shape[1]} must be equal to number of rows in B: {b.shape[0]}")
    # because I transposed b, the shape of the new array is (row a, row b) 
    else:
        while outer < columns:
            inner = 0
            rows = c.shape[0] # number of columns in transposed b
            while inner < rows:
                result.append((a[outer] * c[inner]).sum())
                inner += 1
            outer += 1
        result = np.array(result).reshape((a.shape[0], b.shape[0])) 
        return result

test = np.random.randint(3, 10, (4, 6))

mat_multiply(a, test)

Number of columns in A: 3 must be equal to number of rows in B: 4


### Problem 6

In [161]:
a = a.T
b = b.T

print(mat_multiply(a, b), "\n")

#confirming my answer
print(mat_multiply(a, b) == a@b)

[[ 15 -48  27]
 [ -2 -74 -49]
 [  3  84  69]] 

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
